covoiturage_frontend_homepage:
    pattern:  /home/{page}
    defaults: { _controller: CovoiturageFrontendBundle:Default:index,page:1 }

covoiturage_frontend_voyage_publish:
    pattern:  /navette/publish
    defaults: { _controller: CovoiturageFrontendBundle:Voyage:publish }

covoiturage_frontend_voyage_modify:
    pattern:  /navette/modify/{id}
    defaults: { _controller: CovoiturageFrontendBundle:Voyage:modify }

covoiturage_frontend_voyage_delete:
    pattern:  /navette/delete/{id}
    defaults: { _controller: CovoiturageFrontendBundle:Voyage:delete }

covoiturage_frontend_voyage_user:
    pattern:  /navette/mes-navettes/{page}
    defaults: { _controller: CovoiturageFrontendBundle:User:voyages,page:1 }

######Gov list root###########
covoiturage_frontend_getGouvernorats:
    pattern:  /list/gouvernorats
    defaults: { _controller: CovoiturageFrontendBundle:Place:getGouvernorats }
######Del list root###########
covoiturage_frontend_getDelegations:
    pattern:  /list/delegations
    defaults: { _controller: CovoiturageFrontendBundle:Place:getDelegations }
######Loc list root###########
covoiturage_frontend_getLocations:
    pattern:  /list/locations
    defaults: { _controller: CovoiturageFrontendBundle:Place:getLocations }
######search root###########
covoiturage_frontend_search:
    pattern:  /search
    defaults: { _controller: CovoiturageFrontendBundle:Default:search }